let session=null,monthlyEmployees=[],userRows=[],currentTaskId=null;
const $=id=>document.getElementById(id); const API=()=>window.APP_CONFIG.API_URL;
async function api(action,data={}){const body={action,...data};if(session?.token)body.token=session.token;const r=await fetch(API(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),cache:'no-store'});if(!r.ok)throw new Error('Network error '+r.status);const o=await r.json();if(!o.ok)throw new Error(o.message||'Request failed');return o;}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtTime(v){if(!v)return'';const s=String(v);const m=s.match(/T(\d{2}):(\d{2})/);if(m){let h=+m[1],mi=+m[2];return (h%12||12)+':'+String(mi).padStart(2,'0')+' '+(h>=12?'PM':'AM')}const x=s.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)?/i);if(!x)return s;let h=+x[1],mi=+x[2];if(x[3]){if(x[3].toUpperCase()==='PM'&&h<12)h+=12;if(x[3].toUpperCase()==='AM'&&h===12)h=0}return (h%12||12)+':'+String(mi).padStart(2,'0')+' '+(h>=12?'PM':'AM')}
function timeMinutes(v){const s=String(v||''),m=s.match(/T(\d{2}):(\d{2})/);if(m)return +m[1]*60+ +m[2];const x=s.match(/(\d{1,2}):(\d{2})\s*(AM|PM)?/i);if(!x)return null;let h=+x[1],mi=+x[2];if(x[3]){if(x[3].toUpperCase()==='PM'&&h<12)h+=12;if(x[3].toUpperCase()==='AM'&&h===12)h=0}return h*60+mi}
function dutyMinutes(r){const a=timeMinutes(r.InTime),b=timeMinutes(r.OutTime);return a===null||b===null?'':Math.max(0,b-a-Number(r.BreakMinutes||0))}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id)?.classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));loadPage(id)}
async function loadPage(id){try{if(id==='home')await loadStats();else if(id==='attendance')await loadAttendance();else if(id==='tasks')await loadTasks();else if(id==='users')await loadUsers();else if(id==='templates')await loadTemplates();else if(id==='monthly')await loadMonthly();else if(id==='mytasks')await loadMyTasks();else if(id==='reports')await loadReports();else if(id==='requests')await loadRequests();else if(id==='approvals')await loadApprovals();else if(id==='audit')await loadAudit()}catch(e){console.error(e);alert(e.message)}}
function table(id,rows,cols){const t=$(id);if(!t)return;if(!rows?.length){t.innerHTML='<tbody><tr><td>No records found.</td></tr></tbody>';return}const keys=cols||Object.keys(rows[0]);t.innerHTML='<thead><tr>'+keys.map(k=>'<th>'+esc(k)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+'</tr>').join('')+'</tbody>'}
async function loadStats(){const r=await api('stats');$('statAttendance').textContent=r.attendance;$('statOpen').textContent=r.openTasks;$('statOverdue').textContent=r.overdue;$('statTemplates').textContent=r.templates;$('statOnTime').textContent=r.onTime+'%'}
async function loadAttendance(){const r=await api('attendance.list');const rows=r.rows.map(x=>({...x,InTime:fmtTime(x.InTime),OutTime:fmtTime(x.OutTime),DutyMinutes:dutyMinutes(x)}));renderAttendanceTable(rows);await loadAttendanceSelectors()}
function renderAttendanceTable(rows){const t=$('attendanceTable'),manager=['Admin','Master Admin','HOD'].includes(session.role),keys=['Date','EmployeeId','Name','InTime','OutTime','TaskMinutes','BreakMinutes','DutyMinutes','Weekoff','ApprovalStatus','ApprovedBy'];let html='<thead><tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+(manager?'<th>Approval</th>':'')+'</tr></thead><tbody>';if(!rows.length)html+='<tr><td colspan="12">No attendance records.</td></tr>';else rows.forEach(r=>{let a='';if(manager&&r.ApprovalStatus==='Pending')a='<td><button class="approveAttendance" data-eid="'+esc(r.EmployeeId)+'" data-date="'+esc(r.Date)+'">Approve</button> <button class="rejectAttendance danger" data-eid="'+esc(r.EmployeeId)+'" data-date="'+esc(r.Date)+'">Reject</button></td>';else if(manager)a='<td>'+esc(r.ApprovalStatus||'')+'</td>';html+='<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+a+'</tr>'});t.innerHTML=html+'</tbody>';document.querySelectorAll('.approveAttendance').forEach(b=>b.onclick=()=>approveAttendance(b.dataset.eid,b.dataset.date,'Approved'));document.querySelectorAll('.rejectAttendance').forEach(b=>b.onclick=()=>approveAttendance(b.dataset.eid,b.dataset.date,'Rejected'))}
async function approveAttendance(eid,date,status){try{await api('attendance.approve',{employeeId:eid,date,status,comment:status==='Rejected'?(prompt('Reason (optional):')||''):''});await loadAttendance();await loadNotifications()}catch(e){alert(e.message)}}
async function loadAttendanceSelectors(){populateMonthYear();if(!['Admin','Master Admin','HOD'].includes(session.role)){$('attEmployee').innerHTML='<option value="'+esc(session.employeeId)+'">'+esc(session.name)+' ('+esc(session.employeeId)+')</option>';return}const r=await api('attendance.employees');$('attEmployee').innerHTML='<option value="">Select Employee</option>'+r.rows.map(x=>'<option value="'+esc(x.EmployeeId)+'">'+esc(x.Name)+' — '+esc(x.EmployeeId)+'</option>').join('')}
function populateMonthYear(){const now=new Date(),months=Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0'));$('attMonth').innerHTML=months.map((m,i)=>'<option value="'+m+'">'+new Date(2000,i,1).toLocaleString('en',{month:'long'})+'</option>').join('');$('attMonth').value=String(now.getMonth()+1).padStart(2,'0');$('attYear').innerHTML='';for(let y=now.getFullYear()-2;y<=now.getFullYear()+1;y++)$('attYear').innerHTML+='<option>'+y+'</option>';$('attYear').value=String(now.getFullYear())}
async function loadEmployeeAttendance(){const eid=$('attEmployee').value;if(!eid)return;const r=await api('attendance.employee',{employeeId:eid,month:$('attMonth').value,year:$('attYear').value});table('employeeAttendanceTable',r.rows.map(x=>({...x,InTime:fmtTime(x.InTime),OutTime:fmtTime(x.OutTime),DutyMinutes:dutyMinutes(x)})),['Date','InTime','OutTime','TaskMinutes','BreakMinutes','DutyMinutes','ApprovalStatus','ApprovedBy'])}
function taskActionButtons(r){const mine=String(r.EmployeeId)===String(session.employeeId),manager=['Admin','Master Admin','HOD'].includes(session.role);let a='<button class="taskDetailBtn" data-id="'+esc(r.TaskId)+'">View</button>';if(mine&&!['Completed','Closed'].includes(String(r.Status)))a+=' <button class="taskStartBtn" data-id="'+esc(r.TaskId)+'">Start</button> <button class="taskPauseBtn ghost" data-id="'+esc(r.TaskId)+'">Pause</button> <button class="taskResumeBtn ghost" data-id="'+esc(r.TaskId)+'">Resume</button> <button class="taskCompleteBtn ghost" data-id="'+esc(r.TaskId)+'">Request Completion</button>';if(manager)a+=' <button class="taskReassignBtn ghost" data-id="'+esc(r.TaskId)+'">Reassign</button>';return a}
async function loadTasks(){const r=await api('tasks.list');renderTaskTable('tasksTable',r.rows)}
async function loadMyTasks(){const r=await api('tasks.list');renderTaskTable('myTasksTable',r.rows,true)}
function renderTaskTable(id,rows,my=false){const t=$(id);const keys=my?['TaskId','TaskName','Category','Priority','Frequency','DueDate','PlannedMinutes','ActualMinutes','Status','Overdue']:['TaskId','EmployeeName','Department','TaskName','Category','Priority','Frequency','DueDate','PlannedMinutes','ActualMinutes','Status','Overdue'];if(!rows.length){t.innerHTML='<tbody><tr><td>No tasks.</td></tr></tbody>';return}t.innerHTML='<thead><tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+'<th>Action</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+'<td>'+taskActionButtons(r)+'</td></tr>').join('')+'</tbody>';bindTaskButtons()}
function bindTaskButtons(){document.querySelectorAll('.taskDetailBtn').forEach(b=>b.onclick=()=>openTaskDetail(b.dataset.id));document.querySelectorAll('.taskStartBtn').forEach(b=>b.onclick=()=>taskTimer(b.dataset.id,'start'));document.querySelectorAll('.taskPauseBtn').forEach(b=>b.onclick=()=>taskTimer(b.dataset.id,'pause'));document.querySelectorAll('.taskResumeBtn').forEach(b=>b.onclick=()=>taskTimer(b.dataset.id,'resume'));document.querySelectorAll('.taskCompleteBtn').forEach(b=>b.onclick=()=>requestCompletion(b.dataset.id));document.querySelectorAll('.taskReassignBtn').forEach(b=>b.onclick=()=>reassignTask(b.dataset.id))}
async function taskTimer(id,action){try{await api('task.timer.'+action,{taskId:id});await loadTasks();await loadMyTasks();if(currentTaskId===id)await openTaskDetail(id)}catch(e){alert(e.message)}}
async function requestCompletion(id){try{await api('task.approval.request',{taskId:id});await loadTasks();await loadMyTasks();await loadNotifications()}catch(e){alert(e.message)}}
async function reassignTask(id){const eid=prompt('Enter Active Employee ID for reassignment:');if(!eid)return;try{await api('task.reassign',{taskId:id,employeeId:eid});await loadTasks();await loadNotifications()}catch(e){alert(e.message)}}
async function openTaskDetail(id){currentTaskId=id;$('taskDetail').classList.remove('hidden');try{const r=await api('task.detail',{taskId:id});const t=r.task;$('taskDetailTitle').textContent=t.TaskName;$('taskMeta').innerHTML=['TaskId','EmployeeName','Department','Category','Priority','Frequency','DueDate','PlannedMinutes','ActualMinutes','Status','Overdue'].map(k=>'<div><span>'+esc(k)+'</span><b>'+esc(t[k])+'</b></div>').join('');$('taskTimeline').innerHTML=(r.activity||[]).map(a=>'<div class="timeline-item"><b>'+esc(a.Action)+'</b><small>'+esc(a.Timestamp)+'</small><div>'+esc(a.Details)+'</div></div>').join('')||'<div class="muted">No activity.</div>';$('taskAttachments').innerHTML=(r.attachments||[]).map(a=>'<div><a href="'+esc(a.Url)+'" target="_blank" rel="noopener">'+esc(a.FileName)+'</a> <small>'+esc(a.UploadedBy)+'</small></div>').join('')||'<div class="muted">No attachments.</div>';$('taskStart').disabled=!['Assigned','Paused'].includes(t.Status);$('taskPause').disabled=t.Status!=='In Progress';$('taskResume').disabled=t.Status!=='Paused';$('taskBeforeComplete').disabled=!['In Progress','Paused'].includes(t.Status)}catch(e){alert(e.message)}}
async function addComment(){if(!currentTaskId)return;const text=$('taskCommentText').value.trim();if(!text)return;try{await api('task.comment.add',{taskId:currentTaskId,comment:text});$('taskCommentText').value='';await openTaskDetail(currentTaskId)}catch(e){alert(e.message)}}
async function uploadAttachment(){if(!currentTaskId)return;const f=$('taskAttachment').files[0];if(!f)return; if(f.size>10*1024*1024){alert('File is larger than 10 MB.');return}try{const b=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});await api('task.attachment.upload',{taskId:currentTaskId,fileName:f.name,mimeType:f.type||'application/octet-stream',base64:b});$('taskAttachment').value='';await openTaskDetail(currentTaskId)}catch(e){alert(e.message)}}
async function loadUsers(){if(!['Admin','Master Admin'].includes(session.role))return;const r=await api('users.list');userRows=r.rows;renderUsers(userRows)}
function renderUsers(rows){const q=($('userSearch').value||'').toLowerCase(),data=rows.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q)),keys=['EmployeeId','Name','Department','UserId','Role','Status','InTime','OutTime','Weekoff'];$('usersTable').innerHTML=data.length?'<thead><tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+'<th>Action</th></tr></thead><tbody>'+data.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(k==='InTime'||k==='OutTime'?fmtTime(r[k]):r[k])+'</td>').join('')+'<td><button class="editUser" data-id="'+esc(r.EmployeeId)+'">Edit</button> <button class="statusUser danger" data-id="'+esc(r.EmployeeId)+'">'+(r.Status==='Active'?'Deactivate':'Activate')+'</button> <button class="deleteUser danger" data-id="'+esc(r.EmployeeId)+'">Delete</button></td></tr>').join('')+'</tbody>':'<tbody><tr><td>No users.</td></tr></tbody>';document.querySelectorAll('.editUser').forEach(b=>b.onclick=()=>editUser(b.dataset.id));document.querySelectorAll('.statusUser').forEach(b=>b.onclick=()=>toggleUser(b.dataset.id));document.querySelectorAll('.deleteUser').forEach(b=>b.onclick=()=>deleteUser(b.dataset.id))}
function editUser(id){const r=userRows.find(x=>String(x.EmployeeId)===String(id));if(!r)return;$('uEmpId').value=r.EmployeeId||'';$('uName').value=r.Name||'';$('uDepartment').value=r.Department||'';$('uLogin').value=r.UserId||'';$('uPassword').value='';$('uRole').value=r.Role||'Employee';$('uStatus').value=r.Status==='Deleted'?'Inactive':(r.Status||'Active');$('uIn').value=toInputTime(r.InTime);$('uOut').value=toInputTime(r.OutTime);$('uWeekoff').value=r.Weekoff||'Sunday';$('userMsg').textContent='Editing '+r.Name}
function toInputTime(v){const m=String(v||'').match(/T(\d{2}):(\d{2})/);if(m)return m[1]+':'+m[2];const x=String(v||'').match(/(\d{1,2}):(\d{2})\s*(AM|PM)?/i);if(!x)return'';let h=+x[1];if(x[3]){if(x[3].toUpperCase()==='PM'&&h<12)h+=12;if(x[3].toUpperCase()==='AM'&&h===12)h=0}return String(h).padStart(2,'0')+':'+x[2]}
async function toggleUser(id){const r=userRows.find(x=>String(x.EmployeeId)===String(id));if(!r)return;try{await api('users.status',{employeeId:id,status:r.Status==='Active'?'Inactive':'Active'});await loadUsers()}catch(e){alert(e.message)}}
async function deleteUser(id){if(!confirm('Delete this user? History will be preserved.'))return;try{await api('users.delete',{employeeId:id});await loadUsers()}catch(e){alert(e.message)}}
async function loadTemplates(){const r=await api('templates.list');renderTemplates(r.rows);$('monthlyTemplate').innerHTML='<option value="">Select Template</option>'+r.rows.map(x=>'<option value="'+esc(x.TemplateId)+'">'+esc(x.TemplateName)+' — '+esc(x.Frequency)+'</option>').join('')}
function renderTemplates(rows){const t=$('templatesTable'),keys=['TemplateId','TemplateName','Category','Priority','Frequency','DefaultMinutes','Status'];t.innerHTML=rows.length?'<thead><tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+'<th>Action</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+'<td><button class="editTemplate" data-id="'+esc(r.TemplateId)+'">Edit</button> <button class="deleteTemplate danger" data-id="'+esc(r.TemplateId)+'">Archive</button></td></tr>').join('')+'</tbody>':'<tbody><tr><td>No templates.</td></tr></tbody>';document.querySelectorAll('.editTemplate').forEach(b=>b.onclick=()=>editTemplate(b.dataset.id));document.querySelectorAll('.deleteTemplate').forEach(b=>b.onclick=async()=>{if(confirm('Archive template? Existing generated tasks will remain.')){await api('templates.delete',{templateId:b.dataset.id});await loadTemplates()}})}
function editTemplate(id){api('templates.list').then(r=>{const t=r.rows.find(x=>String(x.TemplateId)===String(id));if(!t)return;$('templateEditor').classList.remove('hidden');$('templateId').value=t.TemplateId;$('templateName').value=t.TemplateName||'';$('templateDetails').value=t.TaskDetails||'';$('templateCategory').value=t.Category||'';$('templatePriority').value=t.Priority||'Normal';$('templateFrequency').value=t.Frequency||'Monthly';$('templateMinutes').value=t.DefaultMinutes||0;let w=[];try{w=JSON.parse(t.WorkItems||'[]')}catch(e){}$('templateWorks').value=w.map(x=>x.WorkName||'').join('\n')})}
async function loadMonthly(){await loadTemplates()}
async function loadMonthlyEmployees(){const r=await api('monthly.employees');monthlyEmployees=r.rows;renderMonthlyEmployees()}
function renderMonthlyEmployees(){const t=$('employeeAssignmentTable');t.innerHTML=monthlyEmployees.length?'<thead><tr><th></th><th>Employee Name</th><th>Employee ID</th><th>Department</th></tr></thead><tbody>'+monthlyEmployees.map(e=>'<tr><td><input class="empCheck" type="checkbox" value="'+esc(e.EmployeeId)+'"></td><td>'+esc(e.Name)+'</td><td>'+esc(e.EmployeeId)+'</td><td>'+esc(e.Department)+'</td></tr>').join('')+'</tbody>':'<tbody><tr><td>No active employees.</td></tr></tbody>'}
function selectedIds(){return Array.from(document.querySelectorAll('.empCheck:checked')).map(x=>x.value)}
async function loadRequests(){table('requestsTable',(await api('requests.list')).rows,['RequestId','Type','StartDate','EndDate','Status','Details','DecisionComment'])}
async function loadApprovals(){const r=await api('approvals.list');const t=$('approvalsTable');if(!r.rows.length){t.innerHTML='<tbody><tr><td>No pending approvals.</td></tr></tbody>';return}t.innerHTML='<thead><tr><th>Type</th><th>Employee</th><th>Department</th><th>Title</th><th>Date</th><th>Details</th><th>Action</th></tr></thead><tbody>'+r.rows.map(x=>'<tr><td>'+esc(x.Type)+'</td><td>'+esc(x.EmployeeName)+' ('+esc(x.EmployeeId)+')</td><td>'+esc(x.Department)+'</td><td>'+esc(x.Title)+'</td><td>'+esc(x.Date)+'</td><td>'+esc(x.Details)+'</td><td><button class="approvalApprove" data-type="'+esc(x.Type)+'" data-id="'+esc(x.Id)+'">Approve</button> <button class="approvalReject danger" data-type="'+esc(x.Type)+'" data-id="'+esc(x.Id)+'">Reject</button></td></tr>').join('')+'</tbody>';document.querySelectorAll('.approvalApprove').forEach(b=>b.onclick=()=>decideApproval(b.dataset.type,b.dataset.id,'Approved'));document.querySelectorAll('.approvalReject').forEach(b=>b.onclick=()=>decideApproval(b.dataset.type,b.dataset.id,'Rejected'))}
async function decideApproval(type,id,status){try{const comment=status==='Rejected'?(prompt('Reason (optional):')||''):'';if(type==='Attendance'){const p=id.split('|');await api('attendance.approve',{employeeId:p[0],date:p[1],status,comment})}else if(type==='Task')await api('task.approval.decide',{taskId:id,status,comment});else await api('request.decide',{requestId:id,status,comment});await loadApprovals();await loadNotifications()}catch(e){alert(e.message)}}
async function loadReports(){table('reportTable',(await api('reports.list')).rows)}async function loadAudit(){table('auditTable',(await api('audit.list')).rows)}
async function loadNotifications(){try{const r=await api('notifications.list'),list=r.rows||[],unread=list.filter(n=>n.status!=='Read').length;$('notificationCount').textContent=unread;$('notificationCount').classList.toggle('hidden',!unread);$('notificationList').innerHTML='<div class="notification-actions"><button id="markAllNotifications" class="ghost">Mark all read</button></div>'+(list.length?list.map(n=>'<button class="notification-item '+(n.status==='Read'?'read':'unread')+'" data-notification="'+esc(n.NotificationId)+'"><b>'+esc(n.title)+'</b><div>'+esc(n.message)+'</div><small>'+esc(n.time)+'</small></button>').join(''):'<div class="notification-item">No notifications.</div>');document.querySelectorAll('[data-notification]').forEach(b=>b.onclick=async()=>{await api('notifications.read',{notificationId:b.dataset.notification});await loadNotifications()});$('markAllNotifications')?.addEventListener('click',async()=>{await api('notifications.readAll');await loadNotifications()})}catch(e){console.log(e.message)}}
$('notificationBtn').onclick=()=>{$('notificationPanel').classList.toggle('hidden');if(!$('notificationPanel').classList.contains('hidden'))loadNotifications()};$('closeNotifications').onclick=()=>$('notificationPanel').classList.add('hidden');
$('loginBtn').onclick=async()=>{try{const r=await api('login',{userId:$('loginId').value.trim(),password:$('loginPassword').value});session={...r.user,token:r.token};localStorage.setItem(window.APP_CONFIG.SESSION_KEY,JSON.stringify(session));boot()}catch(e){$('loginMsg').textContent=e.message}};
function boot(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userName').textContent=session.name;$('roleBadge').textContent=session.role;document.querySelectorAll('.adminOnly').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin'].includes(session.role)));document.querySelectorAll('.adminOrHod').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin','HOD'].includes(session.role)));document.querySelectorAll('.managerOnly').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin','HOD'].includes(session.role)));showPage('home');loadNotifications()}
$('logoutBtn').onclick=()=>{localStorage.removeItem(window.APP_CONFIG.SESSION_KEY);location.reload()};document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>showPage(x.dataset.page));
$('saveAttendance').onclick=async()=>{try{await api('attendance.save',{date:$('attDate').value,inTime:$('attIn').value,outTime:$('attOut').value,taskMinutes:$('attTaskMinutes').value,breakMinutes:$('attBreak').value,weekoff:$('attWeekoff').value});$('attendanceMsg').textContent='Attendance submitted for approval.';await loadAttendance();loadNotifications()}catch(e){$('attendanceMsg').textContent=e.message}};$('refreshAttendance').onclick=loadAttendance;$('loadEmployeeAttendance').onclick=loadEmployeeAttendance;
$('saveTask').onclick=async()=>{try{await api('tasks.save',{employeeId:$('taskEmployeeId').value,taskName:$('taskName').value,details:$('taskDetails').value,category:$('taskCategory').value,priority:$('taskPriority').value,workType:$('taskWorkType').value,dueDate:$('taskDueDate').value,taskMinutes:$('taskMinutes').value});$('taskMsg').textContent='Task assigned.';await loadTasks();loadNotifications()}catch(e){$('taskMsg').textContent=e.message}};$('refreshTasks').onclick=loadTasks;
$('saveUser').onclick=async()=>{try{const r=await api('users.save',{employeeId:$('uEmpId').value,name:$('uName').value,department:$('uDepartment').value,userId:$('uLogin').value,password:$('uPassword').value,role:$('uRole').value,status:$('uStatus').value,officeIn:$('uIn').value,officeOut:$('uOut').value,weekoff:$('uWeekoff').value});$('userMsg').textContent='User saved successfully.';await loadUsers();$('uPassword').value='';api('employee.file.ensure',{employeeId:r.record.EmployeeId}).catch(()=>{})}catch(e){$('userMsg').textContent=e.message}};$('cancelUser').onclick=()=>{['uEmpId','uName','uDepartment','uLogin','uPassword'].forEach(id=>$(id).value='');$('userMsg').textContent=''};$('userSearch').oninput=()=>renderUsers(userRows);
$('newTemplate').onclick=()=>{$('templateEditor').classList.remove('hidden');$('templateId').value='';['templateName','templateDetails','templateCategory','templateMinutes','templateWorks'].forEach(id=>$(id).value='');$('templateFrequency').value='Monthly';$('templatePriority').value='Normal'};$('cancelTemplate').onclick=()=>$('templateEditor').classList.add('hidden');$('saveTemplate').onclick=async()=>{try{await api('templates.save',{templateId:$('templateId').value,templateName:$('templateName').value,details:$('templateDetails').value,category:$('templateCategory').value,priority:$('templatePriority').value,frequency:$('templateFrequency').value,defaultMinutes:$('templateMinutes').value,workItems:$('templateWorks').value});$('templateMsg').textContent='Template saved.';await loadTemplates()}catch(e){$('templateMsg').textContent=e.message}};
$('templateImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const b=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});const r=await api('templates.import',{fileName:f.name,base64:b});$('templateMsg').textContent='Imported '+r.imported+' template(s).';await loadTemplates()}catch(err){$('templateMsg').textContent=err.message}finally{e.target.value=''}};
async function download(action,name){try{const r=await api(action),bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0)),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:r.mimeType}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}}$('exportTemplates').onclick=()=>download('templates.export.xlsx','Task_Templates.xlsx');$('downloadXlsx').onclick=()=>download('templates.format.xlsx','Task_Template_Format.xlsx');$('downloadCsv').onclick=()=>download('templates.format.csv','Task_Template_Format.csv');
$('loadMonthly').onclick=loadMonthlyEmployees;$('selectAllEmployees').onclick=()=>document.querySelectorAll('.empCheck').forEach(x=>x.checked=true);$('clearEmployees').onclick=()=>document.querySelectorAll('.empCheck').forEach(x=>x.checked=false);$('saveEmployeeAssignment').onclick=async()=>{try{const ids=selectedIds(),tid=$('monthlyTemplate').value,month=$('monthlyMonth').value;if(!tid||!month||!ids.length)throw new Error('Select template, month and employees.');const r=await api('monthly.assign',{templateId:tid,month,employeeIds:ids});$('monthlyMsg').textContent='Saved for '+r.saved+' employee(s).'}catch(e){$('monthlyMsg').textContent=e.message}};$('generateMonthly').onclick=async()=>{try{const ids=selectedIds(),tid=$('monthlyTemplate').value,month=$('monthlyMonth').value;if(!tid||!month||!ids.length)throw new Error('Select template, month and employees.');const r=await api('monthly.generate',{templateId:tid,month,employeeIds:ids});$('monthlyMsg').textContent='Generated '+r.generated+' new task group(s). Existing tasks preserved.';await loadTasks()}catch(e){$('monthlyMsg').textContent=e.message}};
$('refreshMyTasks').onclick=loadMyTasks;$('refreshRequests').onclick=loadRequests;$('refreshApprovals').onclick=loadApprovals;$('saveRequest').onclick=async()=>{try{await api('request.save',{type:$('requestType').value,startDate:$('requestStart').value,endDate:$('requestEnd').value,details:$('requestDetails').value});$('requestMsg').textContent='Request submitted for approval.';await loadRequests();await loadNotifications()}catch(e){$('requestMsg').textContent=e.message}};$('refreshAudit').onclick=loadAudit;$('reportSearch').oninput=()=>{const q=$('reportSearch').value.toLowerCase();document.querySelectorAll('#reportTable tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')};
$('closeTaskDetail').onclick=()=>$('taskDetail').classList.add('hidden');$('taskStart').onclick=()=>taskTimer(currentTaskId,'start');$('taskPause').onclick=()=>taskTimer(currentTaskId,'pause');$('taskResume').onclick=()=>taskTimer(currentTaskId,'resume');$('taskBeforeComplete').onclick=()=>requestCompletion(currentTaskId);$('taskReassign').onclick=()=>reassignTask(currentTaskId);$('addTaskComment').onclick=addComment;$('uploadTaskAttachment').onclick=uploadAttachment;
$('attDate').value=new Date().toISOString().slice(0,10);$('monthlyMonth').value=new Date().toISOString().slice(0,7);$('requestStart').value=new Date().toISOString().slice(0,10);$('requestEnd').value=new Date().toISOString().slice(0,10);populateMonthYear();try{const s=JSON.parse(localStorage.getItem(window.APP_CONFIG.SESSION_KEY)||'null');if(s?.token){session=s;boot()}}catch(e){localStorage.removeItem(window.APP_CONFIG.SESSION_KEY)}
