let session=null, monthlyEmployees=[];
const $=id=>document.getElementById(id);
async function api(action,data={}){const body={action,...data};if(session?.token)body.token=session.token;const res=await fetch(window.APP_CONFIG.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const out=await res.json();if(!out.ok)throw new Error(out.message||'Request failed');return out}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));loadPage(id)}
async function loadPage(id){try{if(id==='home'){const r=await api('stats');$('statAttendance').textContent=r.attendance;$('statTasks').textContent=r.openTasks;$('statTemplates').textContent=r.templates;$('statRole').textContent=session.role}if(id==='attendance')loadAttendance();if(id==='tasks')loadTasks();if(id==='templates')loadTemplates();if(id==='monthly')loadMonthlyTemplates();if(id==='employees')loadUsers()}catch(e){alert(e.message)}}
async function loadAttendance(){renderTable('attendanceTable',(await api('attendance.list')).rows)}
async function loadTasks(){renderTable('tasksTable',(await api('tasks.list')).rows)}
async function loadTemplates(){renderTable('templatesTable',(await api('templates.list')).rows,['Edit','Delete'])}
async function loadUsers(){if(!['Admin','Master Admin'].includes(session.role))return;renderTable('usersTable',(await api('users.list')).rows,['Edit'])}
function renderTable(id,rows,actions=[]){const t=$(id);if(!rows?.length){t.innerHTML='<tr><td>No records</td></tr>';return}const keys=Object.keys(rows[0]);t.innerHTML='<thead><tr>'+keys.map(k=>`<th>${esc(k)}</th>`).join('')+(actions.length?'<th>Action</th>':'')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+keys.map(k=>`<td>${esc(row[k])}</td>`).join('')+(actions.length?`<td>${actions.includes('Edit')?`<button onclick='editRow(${JSON.stringify(row)})'>Edit</button>`:''} ${actions.includes('Delete')?`<button class="ghost" onclick='deleteTemplate("${esc(row.TemplateId)}")'>Delete</button>`:''}</td>`:'')+'</tr>').join('')+'</tbody>'}
function editRow(row){if(row.TemplateId!==undefined){$('templateEditor').classList.remove('hidden');$('templateId').value=row.TemplateId;$('templateName').value=row.TemplateName||'';$('templateDetails').value=row.Details||'';$('templateCategory').value=row.Category||'';$('templatePriority').value=row.Priority||'Normal';$('templateFrequency').value=row.Frequency||row.WorkType||'Monthly';$('templateMinutes').value=row.DefaultMinutes||0}else{$('userEditor').classList.remove('hidden');$('uEmpId').value=row.EmployeeId||'';$('uName').value=row.Name||'';$('uDepartment').value=row.Department||'';$('uLogin').value=row.UserId||'';$('uPassword').value='';$('uRole').value=row.Role||'Employee';$('uIn').value=row.OfficeIn||'';$('uOut').value=row.OfficeOut||'';$('uWeekoff').value=row.Weekoff||''}}
async function deleteTemplate(id){if(!confirm('Delete this template? Existing generated employee tasks will NOT be deleted.'))return;try{await api('templates.delete',{templateId:id});loadTemplates()}catch(e){alert(e.message)}}
async function downloadFile(action,data,name){const r=await api(action,data);const bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0));const blob=new Blob([bytes],{type:r.mimeType});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadMonthlyTemplates(){const r=await api('templates.list');const s=$('monthlyTemplate');s.innerHTML='<option value="">Select Template</option>'+r.rows.filter(x=>String(x.Status||'Active')!=='Inactive').map(x=>`<option value="${esc(x.TemplateId)}">${esc(x.TemplateName)} — ${esc(x.Category||'')}</option>`).join('')}
async function loadMonthlyEmployees(){const r=await api('monthly.employees');monthlyEmployees=r.rows;renderEmployeeAssignments()}
function renderEmployeeAssignments(){const t=$('employeeAssignmentTable');if(!monthlyEmployees.length){t.innerHTML='<tr><td>No active employees found.</td></tr>';return}t.innerHTML='<thead><tr><th>Select</th><th>Employee Name</th><th>Employee ID</th><th>Department</th></tr></thead><tbody>'+monthlyEmployees.map((e,i)=>`<tr><td><input class="empCheck" data-index="${i}" type="checkbox" ${e.selected?'checked':''}></td><td>${esc(e.Name)}</td><td>${esc(e.EmployeeId)}</td><td>${esc(e.Department)}</td></tr>`).join('')+'</tbody>'}
function selectedEmployeeIds(){return [...document.querySelectorAll('.empCheck:checked')].map(x=>monthlyEmployees[Number(x.dataset.index)].EmployeeId)}
$('loginBtn').onclick=async()=>{try{const r=await api('login',{userId:$('loginId').value.trim(),password:$('loginPassword').value});session=r.user;session.token=r.token;localStorage.setItem(window.APP_CONFIG.SESSION_KEY,JSON.stringify(session));$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userName').textContent=session.name;$('roleBadge').textContent=' • '+session.role;document.querySelectorAll('.adminOnly').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin'].includes(session.role)));document.querySelectorAll('.adminOrHod').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin','HOD'].includes(session.role)));showPage('home')}catch(e){$('loginMsg').textContent=e.message}}
$('logoutBtn').onclick=()=>{localStorage.removeItem(window.APP_CONFIG.SESSION_KEY);location.reload()};document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>showPage(x.dataset.page));
$('saveAttendance').onclick=async()=>{try{await api('attendance.save',{date:$('attDate').value,inTime:$('attIn').value,outTime:$('attOut').value,taskMinutes:$('attTaskMinutes').value,breakMinutes:$('attBreak').value,weekoff:$('attWeekoff').value});$('attendanceMsg').textContent='Attendance saved.';loadAttendance()}catch(e){$('attendanceMsg').textContent=e.message}}
$('saveTask').onclick=async()=>{try{await api('tasks.save',{employeeId:$('taskEmployeeId').value,taskName:$('taskName').value,details:$('taskDetails').value,category:$('taskCategory').value,priority:$('taskPriority').value,workType:$('taskWorkType').value,dueDate:$('taskDueDate').value,taskMinutes:$('taskMinutes').value});$('taskMsg').textContent='Task assigned.';loadTasks()}catch(e){$('taskMsg').textContent=e.message}}
$('newTemplate').onclick=()=>{$('templateEditor').classList.remove('hidden');['templateId','templateName','templateDetails','templateCategory','templateMinutes'].forEach(id=>$(id).value='');$('templatePriority').value='Normal';$('templateFrequency').value='Monthly'};$('cancelTemplate').onclick=()=>$('templateEditor').classList.add('hidden');
$('saveTemplate').onclick=async()=>{try{await api('templates.save',{templateId:$('templateId').value,templateName:$('templateName').value,details:$('templateDetails').value,category:$('templateCategory').value,priority:$('templatePriority').value,frequency:$('templateFrequency').value,defaultMinutes:$('templateMinutes').value});$('templateEditor').classList.add('hidden');$('templateMsg').textContent='Template saved.';loadTemplates()}catch(e){$('templateMsg').textContent=e.message}}
$('templateImport').onchange=async e=>{const input=e.target;const file=input.files[0];if(!file)return;try{const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});const out=await api('templates.import',{fileName:file.name,mimeType:file.type,base64});$('templateMsg').textContent=`Imported ${out.imported} template row(s).`;loadTemplates()}catch(err){$('templateMsg').textContent=err.message}finally{input.value=''}};
$('exportTemplates').onclick=()=>downloadFile('templates.export.xlsx',{},'Task_Templates.xlsx');$('downloadXlsx').onclick=()=>downloadFile('templates.format.xlsx',{},'Task_Template_Format.xlsx');$('downloadCsv').onclick=()=>downloadFile('templates.format.csv',{},'Task_Template_Format.csv');
$('loadMonthly').onclick=loadMonthlyEmployees;$('monthlyTemplate').onchange=()=>loadMonthlyEmployees();$('selectAllEmployees').onclick=()=>document.querySelectorAll('.empCheck').forEach(x=>x.checked=true);$('clearEmployees').onclick=()=>document.querySelectorAll('.empCheck').forEach(x=>x.checked=false);
$('saveEmployeeAssignment').onclick=async()=>{try{const templateId=$('monthlyTemplate').value,ids=selectedEmployeeIds();if(!templateId)throw new Error('Please select a Task Template.');if(!ids.length)throw new Error('Please select at least one employee.');const r=await api('monthly.assign',{templateId,employeeIds:ids,month:$('monthlyMonth').value});$('monthlyMsg').textContent=`Assignment saved for ${r.saved} employee(s).`;}catch(e){$('monthlyMsg').textContent=e.message}};
$('generateMonthly').onclick=async()=>{try{const templateId=$('monthlyTemplate').value,ids=selectedEmployeeIds();const month=$('monthlyMonth').value;if(!templateId||!ids.length||!month)throw new Error('Select template, employees and month.');const r=await api('monthly.generate',{templateId,employeeIds:ids,month});$('monthlyMsg').textContent=`Generated ${r.generated} new task(s). Existing generated tasks were not deleted.`;loadTasks()}catch(e){$('monthlyMsg').textContent=e.message}};
$('newUser').onclick=()=>{$('userEditor').classList.remove('hidden');['uEmpId','uName','uDepartment','uLogin','uPassword','uIn','uOut','uWeekoff'].forEach(id=>$(id).value='');$('uRole').value='Employee'};$('cancelUser').onclick=()=>$('userEditor').classList.add('hidden');
$('saveUser').onclick=async()=>{try{await api('users.save',{employeeId:$('uEmpId').value,name:$('uName').value,department:$('uDepartment').value,userId:$('uLogin').value,password:$('uPassword').value,role:$('uRole').value,officeIn:$('uIn').value,officeOut:$('uOut').value,weekoff:$('uWeekoff').value});$('userMsg').textContent='User saved.';loadUsers()}catch(e){$('userMsg').textContent=e.message}};$('refreshAttendance').onclick=loadAttendance;$('refreshTasks').onclick=loadTasks;$('attDate').value=new Date().toISOString().slice(0,10);$('monthlyMonth').value=new Date().toISOString().slice(0,7);
try{const s=JSON.parse(localStorage.getItem(window.APP_CONFIG.SESSION_KEY));if(s?.token){session=s;$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userName').textContent=s.name;$('roleBadge').textContent=' • '+s.role;document.querySelectorAll('.adminOnly').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin'].includes(s.role)));document.querySelectorAll('.adminOrHod').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin','HOD'].includes(s.role)));showPage('home')}}catch(e){}
