let session=null,monthlyEmployees=[];const $=id=>document.getElementById(id);const API=()=>window.APP_CONFIG.API_URL;
async function api(action,data={}){const body={action,...data};if(session?.token)body.token=session.token;const r=await fetch(API(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),cache:'no-store'});if(!r.ok)throw new Error('Network error '+r.status);const o=await r.json();if(!o.ok)throw new Error(o.message||'Request failed');return o;}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id)?.classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));loadPage(id)}
async function loadPage(id){try{if(id==='home')loadStats();else if(id==='attendance')loadAttendance();else if(id==='tasks')loadTasks();else if(id==='users')loadUsers();else if(id==='templates')loadTemplates();else if(id==='monthly')loadMonthly();else if(id==='mytasks')loadMyTasks();else if(id==='reports')loadReports();else if(id==='audit')loadAudit()}catch(e){alert(e.message)}}
async function loadStats(){const r=await api('stats');$('statAttendance').textContent=r.attendance;$('statOpen').textContent=r.openTasks;$('statOverdue').textContent=r.overdue;$('statTemplates').textContent=r.templates;$('statOnTime').textContent=r.onTime+'%'}
function table(id,rows,cols){const t=$(id);if(!t)return;if(!rows?.length){t.innerHTML='<tr><td>No records found.</td></tr>';return}const keys=cols||Object.keys(rows[0]);t.innerHTML='<thead><tr>'+keys.map(k=>'<th>'+esc(k)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+'</tr>').join('')+'</tbody>'}
async function loadAttendance(){table('attendanceTable',(await api('attendance.list')).rows)}
async function loadTasks(){const rows=(await api('tasks.list')).rows;const t=$('tasksTable');if(!rows.length){t.innerHTML='<tr><td>No tasks.</td></tr>';return}const keys=['TaskId','EmployeeName','Department','TaskName','Category','Priority','Frequency','DueDate','PlannedMinutes','ActualMinutes','Status'];t.innerHTML='<thead><tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+'<th>Action</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+'<td><select class="statusSel" data-id="'+esc(r.TaskId)+'"><option>Assigned</option><option>Accepted</option><option>In Progress</option><option>Before Completion</option><option>Completed</option><option>Closed</option><option>On Hold</option></select></td></tr>').join('')+'</tbody>';document.querySelectorAll('.statusSel').forEach(s=>s.value=rows.find(r=>String(r.TaskId)===s.dataset.id)?.Status||'Assigned');document.querySelectorAll('.statusSel').forEach(s=>s.onchange=async()=>{try{await api('tasks.update',{taskId:s.dataset.id,status:s.value});loadStats()}catch(e){alert(e.message)}})}
async function loadMyTasks(){table('myTasksTable',(await api('tasks.list')).rows)}
async function loadUsers(){if(!['Admin','Master Admin'].includes(session.role))return;const rows=(await api('users.list')).rows;const keys=['EmployeeId','Name','Department','UserId','Role','Status','OfficeIn','OfficeOut','Weekoff'];const t=$('usersTable');t.innerHTML=rows.length?'<thead><tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+'<th>Action</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+'<td><button class="editUser" data-id="'+esc(r.EmployeeId)+'">Edit</button></td></tr>').join('')+'</tbody>':'<tr><td>No users.</td></tr>';document.querySelectorAll('.editUser').forEach(b=>b.onclick=()=>editUser(b.dataset.id,rows))}
function editUser(id,rows){const r=rows.find(x=>String(x.EmployeeId)===id);if(!r)return;$('userEditor').classList.remove('hidden');$('uEmpId').value=r.EmployeeId||'';$('uName').value=r.Name||'';$('uDepartment').value=r.Department||'';$('uLogin').value=r.UserId||'';$('uPassword').value='';$('uRole').value=r.Role||'Employee';$('uStatus').value=r.Status||'Active';$('uIn').value=r.OfficeIn||'';$('uOut').value=r.OfficeOut||'';$('uWeekoff').value=r.Weekoff||''}
async function loadTemplates(){const rows=(await api('templates.list')).rows;const t=$('templatesTable');const keys=['TemplateId','TemplateName','TaskDetails','Category','Priority','Frequency','DefaultMinutes','Status'];t.innerHTML=rows.length?'<thead><tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+'<th>Action</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(r[k])+'</td>').join('')+'<td><button class="editTemplate" data-id="'+esc(r.TemplateId)+'">Edit</button> <button class="deleteTemplate danger" data-id="'+esc(r.TemplateId)+'">Delete</button></td></tr>').join('')+'</tbody>':'<tr><td>No templates.</td></tr>';document.querySelectorAll('.editTemplate').forEach(b=>b.onclick=()=>editTemplate(b.dataset.id,rows));document.querySelectorAll('.deleteTemplate').forEach(b=>b.onclick=()=>deleteTemplate(b.dataset.id));$('monthlyTemplate').innerHTML='<option value="">Select Template</option>'+rows.map(r=>'<option value="'+esc(r.TemplateId)+'">'+esc(r.TemplateName)+'</option>').join('')}
function editTemplate(id,rows){const r=rows.find(x=>String(x.TemplateId)===id);if(!r)return;$('templateEditor').classList.remove('hidden');$('templateId').value=r.TemplateId;$('templateName').value=r.TemplateName||'';$('templateDetails').value=r.TaskDetails||'';$('templateCategory').value=r.Category||'';$('templatePriority').value=r.Priority||'Normal';$('templateFrequency').value=r.Frequency||'Monthly';$('templateMinutes').value=r.DefaultMinutes||0;let w=[];try{w=JSON.parse(r.WorkItems||'[]')}catch(e){}$('templateWorks').value=w.map(x=>x.WorkName||'').join('\n')}
async function deleteTemplate(id){if(!confirm('Archive this template? Existing generated tasks will remain.'))return;try{await api('templates.delete',{templateId:id});loadTemplates()}catch(e){alert(e.message)}}
async function download(action,name){const r=await api(action,{}),bytes=Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0)),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:r.mimeType}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadMonthly(){await loadTemplates();await loadMonthlyEmployees()}
async function loadMonthlyEmployees(){const r=await api('monthly.employees');monthlyEmployees=r.rows;renderEmployees()}
function renderEmployees(){const t=$('employeeAssignmentTable');t.innerHTML=monthlyEmployees.length?'<thead><tr><th>Select</th><th>Employee Name</th><th>Employee ID</th><th>Department</th></tr></thead><tbody>'+monthlyEmployees.map((e,i)=>'<tr><td><input class="empCheck" data-i="'+i+'" type="checkbox"></td><td>'+esc(e.Name)+'</td><td>'+esc(e.EmployeeId)+'</td><td>'+esc(e.Department)+'</td></tr>').join('')+'</tbody>':'<tr><td>No active employees.</td></tr>'}
function selectedIds(){return [...document.querySelectorAll('.empCheck:checked')].map(x=>monthlyEmployees[Number(x.dataset.i)].EmployeeId)}
async function loadReports(){table('reportTable',(await api('reports.list')).rows)}async function loadAudit(){table('auditTable',(await api('audit.list')).rows)}
$('loginBtn').onclick=async()=>{try{const r=await api('login',{userId:$('loginId').value.trim(),password:$('loginPassword').value});session={...r.user,token:r.token};localStorage.setItem(window.APP_CONFIG.SESSION_KEY,JSON.stringify(session));boot()}catch(e){$('loginMsg').textContent=e.message}};
function boot(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userName').textContent=session.name;$('roleBadge').textContent=session.role;document.querySelectorAll('.adminOnly').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin'].includes(session.role)));document.querySelectorAll('.adminOrHod').forEach(x=>x.classList.toggle('hidden',!['Admin','Master Admin','HOD'].includes(session.role)));showPage('home')}
$('logoutBtn').onclick=()=>{localStorage.removeItem(window.APP_CONFIG.SESSION_KEY);location.reload()};document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>showPage(x.dataset.page));
$('saveAttendance').onclick=async()=>{try{await api('attendance.save',{date:$('attDate').value,inTime:$('attIn').value,outTime:$('attOut').value,taskMinutes:$('attTaskMinutes').value,breakMinutes:$('attBreak').value,weekoff:$('attWeekoff').value});$('attendanceMsg').textContent='Attendance saved.';loadAttendance()}catch(e){$('attendanceMsg').textContent=e.message}};$('refreshAttendance').onclick=loadAttendance;
$('saveTask').onclick=async()=>{try{await api('tasks.save',{employeeId:$('taskEmployeeId').value,taskName:$('taskName').value,details:$('taskDetails').value,category:$('taskCategory').value,priority:$('taskPriority').value,workType:$('taskWorkType').value,dueDate:$('taskDueDate').value,taskMinutes:$('taskMinutes').value});$('taskMsg').textContent='Task assigned.';loadTasks()}catch(e){$('taskMsg').textContent=e.message}};$('refreshTasks').onclick=loadTasks;
$('newUser').onclick=()=>{$('userEditor').classList.remove('hidden');['uEmpId','uName','uDepartment','uLogin','uPassword','uIn','uOut','uWeekoff'].forEach(id=>$(id).value='');$('uRole').value='Employee';$('uStatus').value='Active'};$('cancelUser').onclick=()=>$('userEditor').classList.add('hidden');$('saveUser').onclick=async()=>{try{await api('users.save',{employeeId:$('uEmpId').value,name:$('uName').value,department:$('uDepartment').value,userId:$('uLogin').value,password:$('uPassword').value,role:$('uRole').value,status:$('uStatus').value,officeIn:$('uIn').value,officeOut:$('uOut').value,weekoff:$('uWeekoff').value});$('userMsg').textContent='User saved.';loadUsers()}catch(e){$('userMsg').textContent=e.message}};
$('newTemplate').onclick=()=>{$('templateEditor').classList.remove('hidden');$('templateId').value='';['templateName','templateDetails','templateCategory','templateMinutes','templateWorks'].forEach(id=>$(id).value='');$('templateFrequency').value='Monthly';$('templatePriority').value='Normal'};$('cancelTemplate').onclick=()=>$('templateEditor').classList.add('hidden');$('saveTemplate').onclick=async()=>{try{await api('templates.save',{templateId:$('templateId').value,templateName:$('templateName').value,details:$('templateDetails').value,category:$('templateCategory').value,priority:$('templatePriority').value,frequency:$('templateFrequency').value,defaultMinutes:$('templateMinutes').value,workItems:$('templateWorks').value});$('templateMsg').textContent='Template saved.';loadTemplates()}catch(e){$('templateMsg').textContent=e.message}};
$('templateImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const b=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});const r=await api('templates.import',{fileName:f.name,base64:b});$('templateMsg').textContent='Imported '+r.imported+' template(s).';loadTemplates()}catch(err){$('templateMsg').textContent=err.message}finally{e.target.value=''}};$('exportTemplates').onclick=()=>download('templates.export.xlsx','Task_Templates.xlsx');$('downloadXlsx').onclick=()=>download('templates.format.xlsx','Task_Template_Format.xlsx');$('downloadCsv').onclick=()=>download('templates.format.csv','Task_Template_Format.csv');
$('loadMonthly').onclick=loadMonthlyEmployees;$('selectAllEmployees').onclick=()=>document.querySelectorAll('.empCheck').forEach(x=>x.checked=true);$('clearEmployees').onclick=()=>document.querySelectorAll('.empCheck').forEach(x=>x.checked=false);$('saveEmployeeAssignment').onclick=async()=>{try{const ids=selectedIds(),tid=$('monthlyTemplate').value,month=$('monthlyMonth').value;if(!tid||!month||!ids.length)throw new Error('Select template, month and employees.');const r=await api('monthly.assign',{templateId:tid,month,employeeIds:ids});$('monthlyMsg').textContent='Saved for '+r.saved+' employee(s).'}catch(e){$('monthlyMsg').textContent=e.message}};$('generateMonthly').onclick=async()=>{try{const ids=selectedIds(),tid=$('monthlyTemplate').value,month=$('monthlyMonth').value;if(!tid||!month||!ids.length)throw new Error('Select template, month and employees.');const r=await api('monthly.generate',{templateId:tid,month,employeeIds:ids});$('monthlyMsg').textContent='Generated '+r.generated+' new task group(s). Existing tasks were preserved.';loadTasks()}catch(e){$('monthlyMsg').textContent=e.message}};
$('refreshMyTasks').onclick=loadMyTasks;$('refreshAudit').onclick=loadAudit;document.addEventListener('input',e=>{if(e.target.id==='reportSearch'){const q=e.target.value.toLowerCase();document.querySelectorAll('#reportTable tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')}});
$('attDate').value=new Date().toISOString().slice(0,10);$('monthlyMonth').value=new Date().toISOString().slice(0,7);try{const s=JSON.parse(localStorage.getItem(window.APP_CONFIG.SESSION_KEY)||'null');if(s?.token){session=s;boot()}}catch(e){localStorage.removeItem(window.APP_CONFIG.SESSION_KEY)}
